Start navbar, and expose it as a page
smartcoop/design-hs pull request #5
Opened 2022-01-08 19:05 UTC by thusc

This draft PR targets the `document` branch.

2022-01-10 17:58 UTC, asheshambasta commented on lib/src/Smart/Html/Navbar.hs
> +  ]
Shouldn't this reside in `Examples.Navbar` (in the executable part of the packge)? 
Also; I since we have `containers` as a dependency, we can use the formal [Tree](https://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-Tree.html#t:Tree) datatype.

I'd also avoid using `Text` but instead use a newtype like `Title` `Body` from the `Types` module. Using these newtypes will allow for type-safety and is usually painless with `OverloadedStrings` thanks to the `IsString` instance.

2022-03-05 23:07 UTC, thusc commented on lib/src/Smart/Html/Navbar.hs
> +  ]
Can you get a new look at this ?

2022-03-06 13:57 UTC, asheshambasta requested changes
Minor comments.

2022-03-06 13:57 UTC, asheshambasta commented on exe/bin/Main.hs
> +              | (fileName, (_, canvas)) <- M.toList components ++ M.toList layouts
Probably better to use `<>` which is more general than `++`. Thus: 
```suggestion
              | (fileName, (_, canvas)) <- M.toList components <> M.toList layouts
```

2022-03-06 13:57 UTC, asheshambasta commented on exe/bin/Main.hs
> +  layoutLinks = foldl' mappend mempty [ H.br >> link' | link' <- layoutLinks' ]
Can we use mconcat; or mapM?

2022-03-06 13:57 UTC, asheshambasta commented on lib/src/Smart/Html/Navbar.hs
> +data Navbar = Navbar [Entry]
Can be `newtype`; thus: 
```suggestion
newtype Navbar = Navbar [Entry]
```

2022-03-06 13:57 UTC, asheshambasta commented on lib/src/Smart/Html/Navbar.hs
> +              H.li ! A.class_ "c-menu__item" $ do
redundant `do`

2022-03-06 13:59 UTC, asheshambasta commented on exe/bin/Main.hs
> +              | (fileName, (_, canvas)) <- M.toList components ++ M.toList layouts
^ @thusc edited the comment above.

2022-03-06 15:29 UTC, asheshambasta commented on exe/bin/Main.hs
> +          | (fileName, (title, _)) <- M.toList layouts
@thusc I believe this comment on the previous PR review was missed; and I made that comment in error. 
`M.toList` ouputs a list of tuples with the keys as fst; but the general toList outputs only the values. 

My bad, and apologies for that.

2022-03-06 15:29 UTC, asheshambasta approved these changes
LGTM.

2022-03-06 15:34 UTC, merged